### PR TITLE
Changed how files are loaded in DefaultFactory

### PR DESCRIPTION
**Pull request by jwmajors81**
The default factory was calling java.util.File.toURL and when that is used it doesn't properly handle some special characters in the file path such as ##.  ## is now included in war file names to support Tomcat's Parallel Deployment feature.  I identified the issue while working on a project and just wanted to inform you of the issue.  There are two commits, involved in this, but really only one change.  I didn't like the first commit because I had custom java formatting enabled in my workspace and that caused the code to look like I changed a lot where in reality this is a very simple change.

### CODE REVIEW

**Comment by eschulma** [comment]
I need this functionality as well. I guess I'll do it on my own if I must but it would be nice to get this merged in.

**Comment by cocogza** [comment]
We also need this fixed in order to take advantage of Tomcat's parallel deployment functionality. 

Could it be merged?

**Comment by eschulma** [comment]
Since there are two pull requests that fix this already in the queue, and there has been no activity since 2013, I'm guessing it won't be done here. However you can download my copy (eschulma) or the two folks who submitted here, and do an ant build with one command. That's what I did and sitemesh is running in production now.

**Comment by codeconsole** [comment]
https://github.com/sitemesh/sitemesh2/pull/19

**Pull request closed without merging**
